# Generated by Django 3.1.3 on 2020-11-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='list',
            name='priority',
            field=models.CharField(default='', max_length=50),
        ),
    ]
