# Generated by Django 3.1.3 on 2020-11-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_auto_20201107_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='subitem',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
