# Generated by Django 3.1.3 on 2020-11-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_list_subitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='subitem',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
    ]
